version: '3'
services:
  digiyatra-controller:
    build: .
    ports:
      - "8120:80"  # Expose a different port for the controller
    environment:
      - AGENT_HOST=host.docker.internal
      # - AGENT_PORT=8020
      - AGENT_PORT=8001
    networks:
      - aca
networks:
  aca: